---
- name: Deploy CLI Tools
  hosts: all
  become: true
  vars_files:
    - tools_versions.yml

  tasks:
    # ---------------------------------------------------------
    # STRATEGY A: Debian Packages (.deb)
    # ---------------------------------------------------------
    
    # 1. Download all .deb files
    - name: "Download .deb tools"
      get_url:
        url: "{{ item.value.url_template | replace('{version}', item.value.version) }}"
        dest: "/tmp/{{ item.key }}.deb"
        checksum: "{{ item.value.checksum | default(omit) }}"
      loop: "{{ tools | dict2items }}"
      when: item.value.install_type == 'deb'
      register: deb_downloads

    # 2. Install them (Looping over the download results)
    - name: "Install .deb via apt"
      apt:
        deb: "{{ item.dest }}"
      # We loop over the results of the previous task
      loop: "{{ deb_downloads.results }}"
      loop_control:
        label: "{{ item.item.key }}"
      # Logic:
      # 1. 'not item.skipped': Ensure we only look at 'deb' types
      # 2. 'item.changed': Only run apt if we downloaded a new file (Optimization)
      #    (Remove 'and item.changed' if you want to force reinstall every run)
      when: not item.skipped | default(false)

    # ---------------------------------------------------------
    # STRATEGY B: Tarballs / Archives
    # ---------------------------------------------------------

    # 1. Download all Archives
    - name: "Download archive tools"
      get_url:
        url: "{{ item.value.url_template | replace('{version}', item.value.version) }}"
        dest: "/tmp/{{ item.key }}.archive"
        checksum: "{{ item.value.checksum | default(omit) }}"
      loop: "{{ tools | dict2items }}"
      when: item.value.install_type == 'tar'
      register: archive_downloads

    # 2. Create extraction directories
    - name: "Create temp extraction directory"
      file:
        path: "/tmp/{{ item.item.key }}_extract"
        state: directory
        mode: '0755'
      loop: "{{ archive_downloads.results }}"
      loop_control:
        label: "{{ item.item.key }}"
      when: not item.skipped | default(false)

    # 3. Extract tarballs
    - name: "Extract tarball to temp directory"
      unarchive:
        src: "{{ item.dest }}"
        dest: "/tmp/{{ item.item.key }}_extract"
        remote_src: yes
      loop: "{{ archive_downloads.results }}"
      loop_control:
        label: "{{ item.item.key }}"
      when: not item.skipped | default(false)
      register: tar_extracts

    # 4. Find and copy the binary to /usr/local/bin
    - name: "Install binary from extracted archive"
      shell: |
        find "/tmp/{{ item.item.item.key }}_extract" -name "{{ item.item.item.value.binary_name }}" -type f -exec cp {} /usr/local/bin/ \;
        chmod 0755 "/usr/local/bin/{{ item.item.item.value.binary_name }}"
        rm -rf "/tmp/{{ item.item.item.key }}_extract"
      loop: "{{ tar_extracts.results }}"
      loop_control:
        label: "{{ item.item.item.key }}"
      when: not item.skipped | default(false)


    # ---------------------------------------------------------
    # STRATEGY B2: Full Directory Tarballs (e.g., neovim)
    # ---------------------------------------------------------

    # 1. Download full directory archives
    - name: "Download full directory archive tools"
      get_url:
        url: "{{ item.value.url_template | replace('{version}', item.value.version) }}"
        dest: "/tmp/{{ item.key }}.archive"
        checksum: "{{ item.value.checksum | default(omit) }}"
      loop: "{{ tools | dict2items }}"
      when: item.value.install_type == 'tar_full'
      register: tar_full_downloads

    # 2. Extract to temp directory
    - name: "Extract full directory tarball"
      unarchive:
        src: "{{ item.dest }}"
        dest: "/tmp/"
        remote_src: yes
      loop: "{{ tar_full_downloads.results }}"
      loop_control:
        label: "{{ item.item.key }}"
      when: not item.skipped | default(false)
      register: tar_full_extracts

    # 3. Copy entire directory structure to /usr/local/
    - name: "Install full directory structure"
      shell: |
        rsync -av "/tmp/{{ item.item.value.extract_dir }}/" /usr/local/
        rm -rf "/tmp/{{ item.item.value.extract_dir }}"
      loop: "{{ tar_full_downloads.results }}"
      loop_control:
        label: "{{ item.item.key }}"
      when: not item.skipped | default(false)

    # ---------------------------------------------------------
    # STRATEGY C: Compressed Binaries (.bz2, .gz, etc.)
    # ---------------------------------------------------------

    # 1. Download compressed binaries
    - name: "Download compressed binary tools"
      get_url:
        url: "{{ item.value.url_template | replace('{version}', item.value.version) }}"
        dest: "/tmp/{{ item.key }}.bz2"
        checksum: "{{ item.value.checksum | default(omit) }}"
        force: yes
      loop: "{{ tools | dict2items }}"
      when: item.value.install_type == 'bz2'
      register: bz2_downloads

    # 2. Decompress and install
    - name: "Decompress and install bz2 binary"
      shell: |
        bunzip2 -c "{{ item.dest }}" > "/usr/local/bin/{{ item.item.value.binary_name }}"
        chmod 0755 "/usr/local/bin/{{ item.item.value.binary_name }}"
      loop: "{{ bz2_downloads.results }}"
      loop_control:
        label: "{{ item.item.key }}"
      when: not item.skipped | default(false)

    # ---------------------------------------------------------
    # STRATEGY D: Shell Scripts
    # ---------------------------------------------------------

    # 1. Download and install scripts directly
    - name: "Download and install script tools"
      get_url:
        url: "{{ item.value.url_template | replace('{version}', item.value.version) }}"
        dest: "/usr/local/bin/{{ item.value.binary_name | default(item.key) }}"
        checksum: "{{ item.value.checksum | default(omit) }}"
        mode: '0755'
      loop: "{{ tools | dict2items }}"
      when: item.value.install_type == 'script'

    # ---------------------------------------------------------
    # STRATEGY E: Direct Binaries
    # ---------------------------------------------------------

    # 1. Download and install pre-compiled binaries directly
    - name: "Download and install binary tools"
      get_url:
        url: "{{ item.value.url_template | replace('{version}', item.value.version) }}"
        dest: "/usr/local/bin/{{ item.value.binary_name }}"
        checksum: "{{ item.value.checksum | default(omit) }}"
        mode: '0755'
      loop: "{{ tools | dict2items }}"
      when: item.value.install_type == 'binary'
